# Generated by Django 5.0.3 on 2024-05-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='attempts_allowed',
            field=models.IntegerField(default=1),
        ),
    ]
