# Generated by Django 5.0.3 on 2024-05-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_attempts_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='deadline_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
