# Generated by Django 5.0.3 on 2024-05-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_quiz_success_criteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='deadline',
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('radio', 'Radio'), ('checkbox', 'Checkbox')], max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='deadline_minutes',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Attempt',
        ),
    ]
