# Generated by Django 5.0.3 on 2024-05-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyticalservice', '0004_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
