# Generated by Django 5.0.3 on 2024-05-08 15:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyticalservice', '0007_feedback_date_alter_enrollment_enrolled_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('user', 'course')},
        ),
    ]
