# Generated by Django 5.0.3 on 2024-05-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyticalservice', '0009_enrollment_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='completed',
        ),
    ]
