# Generated by Django 5.0.3 on 2024-05-10 20:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticalservice', '0013_remove_enrollment_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='completed_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
