# Generated by Django 5.0.3 on 2024-05-14 17:50

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticalservice', '0014_progress_completed_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='completed_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completed_course',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completion_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(check=models.Q(('completed_course', True), ('completion_date__isnull', False)), name='completed_course_check'),
        ),
    ]
