# Generated by Django 5.0.3 on 2024-05-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticalservice', '0016_remove_enrollment_completed_course_check_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='completion_date_null_if_not_completed',
        ),
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='completion_date_not_null_if_completed',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
