# Generated by Django 5.0.3 on 2024-05-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticalservice', '0017_remove_enrollment_completion_date_null_if_not_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='completed_course',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.BooleanField(default=False),
        ),
    ]
