# Generated by Django 5.0.3 on 2024-04-20 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_alter_emailverification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
