# Generated by Django 5.0.3 on 2024-04-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0008_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='is_used',
            field=models.BooleanField(default=True),
        ),
    ]
