# Generated by Django 5.0.3 on 2024-04-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0009_passwordreset_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PasswordReset',
        ),
    ]
