# Generated by Django 5.0.3 on 2024-04-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0015_alter_sitesettings_verification_link_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='invitation_link_expiration',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='verification_link_expiration',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='invitation_link_expiration_days',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='verification_link_expiration_hours',
            field=models.IntegerField(default=5),
        ),
    ]
