# Generated by Django 5.0.3 on 2024-04-30 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0016_remove_sitesettings_invitation_link_expiration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordreset',
            name='is_opened',
        ),
    ]
