# Generated by Django 5.0.3 on 2024-05-03 07:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0018_invitationlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationlink',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
