# Generated by Django 5.0.3 on 2024-05-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0019_invitationlink_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationlink',
            name='token',
        ),
    ]
