# Generated by Django 5.0.3 on 2024-05-03 15:04

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0022_invitationlink_uid_alter_invitationlink_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationlink',
            name='uid',
        ),
        migrations.AlterField(
            model_name='invitationlink',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='invitationlink',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
