# Generated by Django 5.0.3 on 2024-05-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0024_userroles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='is_opened',
        ),
    ]
